POST  http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJwZXJtaXNzaW9ucyI6W10sImlhdCI6MTczNjM1OTQ3NSwiZXhwIjoxNzM2MzYzMDc1LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.d78WjdaQoZs9J2GxqQMWN_ybHYrIu7s0nztBajyHhyA
