POST  http://localhost:3000/coffees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoidGVzdDFAZ21haWwuY29tIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3MzYzNTU5NDMsImV4cCI6MTczNjM1OTU0MywiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.QEAErf-UXUu1NGdeIM0pKuAL7MqJTFYnGfE2bkGkCiQ
